INSERT INTO estados (estado) VALUES
('Aguascalientes'),
('Baja California'),
('Baja California Sur'),
('Campeche'),
('Coahuila'),
('Colima'),
('Chiapas'),
('Chihuahua'),
('Distrito Federal'),
('Durango'),
('Guanajuato'),
('Guerrero'),
('Hidalgo'),
('Jalisco'),
('Mexico'),
('Michoacan'),
('Morelos'),
('Nayarit'),
('Nuevo Leon'),
('Oaxaca'),
('Puebla'),
('Queretaro'),
('Quintana Roo'),
('San Luis Potosi'),
('Sinaloa'),
('Sonora'),
('Tabasco'),
('Tamaulipas'),
('Tlaxcala'),
('Veracruz'),
('Yucatan'),
('Zacatecas');